version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: pogo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pogo
    ports:
      - "5432:5432"
    volumes:
      - pogo_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pogo"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pogo_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pogo
      PORT: 3000
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pogo_pg_data: